### PR TITLE
Add fade-out effect to slides

### PR DESCRIPTION
**Pull request by dennisklad**
Also formatted the code :)

Solves #95 .This was easier to do that I though.

Basically the only code you need is this after the `selectWrapper` definition:
```
// First, hide all modules before showing the new ones
for (let i = 0; i < this.length; i += 1) {
    this[i].hide(this.slideTransitionSpeed, false, { lockString: "mmmc" }); // Hide all modules
}

setTimeout(() => {
    /* The existing code for processing the slides */
    for (let i = 0; i < this.length; i += 1) {
        /*
        * There is currently no easy way to discover whether a module is ALREADY shown/hidden
        * In testing, calling show/hide twice seems to cause no issues
        */
        Log.log(`Processing ${this[i].name}`)
        [.....]
        } else {
            // We aren't using slides and this module shouldn't be shown.
            this[i].hide(0, false, { lockString: "mmmc" });
        }
    }
}, this.slideTransitionSpeed);
```

Disclaimer: 
This works as expected for my configuration with two slides, but should be tested with other modes as well.

### CODE REVIEW

**Comment by KristjanESPERANTO** [comment]
Thanks for the PR! :smiley: 

> Also formatted the code :)

This makes it hard to review. We use ESLint to lint and format the code :slightly_smiling_face:  Please run `npm run lint:fix` to apply the ESLint rules.

**Comment by dennisklad** [comment]
The formatting with `npm run lint:fix` ended with 40 problems. 
image


You basically only need the code after the selectWrapper definition:
```
// First, hide all modules before showing the new ones
for (let i = 0; i < this.length; i += 1) {
    this[i].hide(this.slideTransitionSpeed, false, { lockString: "mmmc" }); // Hide all modules
}

setTimeout(() => {
    /* The existing code for processing the slides */
    for (let i = 0; i < this.length; i += 1) {
        /*
        * There is currently no easy way to discover whether a module is ALREADY shown/hidden
        * In testing, calling show/hide twice seems to cause no issues
        */
        Log.log(`Processing ${this[i].name}`)
        [.....]
        } else {
            // We aren't using slides and this module shouldn't be shown.
            this[i].hide(0, false, { lockString: "mmmc" });
        }
    }
}, this.slideTransitionSpeed);
```

**Comment by KristjanESPERANTO** [comment]
OK, I tested it and checked your changes. I really like the fade-out! :clap: 

But before merging:

1. What do you think, should there be a separate config option to set the fade out? Maybe some people want to configure it asynchronously or like the current behaviour.
2. The README needs updating.

> The formatting with npm run lint:fix ended with 40 problems.

I will take care of it as soon as we are done with this PR.

**Comment by dennisklad** [comment]
Glad you like it! Sure, that is a good point. Why not have two variables:
`SlideFadeInTransition` and `SlideFadeOutTransition`. We can set them both
with the same default value and update the README.

**Comment by KristjanESPERANTO** [comment]
Thank you! I merge it into the develop branch and prepare a new release.

**Pull request merged**
